development:
  host: localhost
  database: setup_meetup_development
  use_activesupport_time_zone: true

test:
  host: localhost
  database: setup_meetup_test
  use_activesupport_time_zone: true

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  use_activesupport_time_zone: true
