development:
  host: localhost
  database: setup_meetup_development

test:
  host: localhost
  database: setup_meetup_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>']
